apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
      environment: production
  template:
    metadata:
      labels:
        app: frontend
        environment: production
    spec:
      containers:
        - name: frontend-container 
          image: httpd
          env:
          - name: BACKEND_IP
            value: "10.96.10.10"
          - name: BACKEND_PORT
            value: "80" 
