apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
  selector:
    app: frontend
    environment: production
