apiVersion: v1
kind: Pod
metadata:
  name: local-pod
spec:
  restartPolicy: Never
  containers:
    - image: ubuntu
      name: ubuntu
      command: ['/bin/bash', '-ec', 'echo "this is a test" > /data/application/data.txt']
      volumeMounts:
        - mountPath: /data/application
          name: local-volume
    - image: ubuntu
      name: ubuntu2
      command: ['/bin/bash', '-ec', 'sleep 10 && cat /data/application/data.txt']
      volumeMounts:
        - mountPath: /data/application
          name: local-volume
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: pvc

