kind: Deployment
apiVersion: apps/v1         # apps group, version 1
metadata:
  name: k8s-for-beginners
spec:
  replicas: 3               # Create 3 pods
  selector:
    matchLabels:
      tier: frontend        # Match the deploy label with the pod label
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: k8s-for-beginners
        image: samirgadkari/k8s-for-beginners:v0.0.1

