kind: Service
apiVersion: v1
metadata:
  name: page-counter
spec:
  selector:                 # Defines the labels to be selected to specify a relationship
    tier: frontend          # with a pod.
  type: NodePort            # Expose a port in each node of the cluster
  ports:
    - port: 80              # Associate <service IP>:<port> with 
      targetPort: 8080        # <pod IP>:<port>

