apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: secret-container
      image: k8s.gcr.io/busybox
      command: ['/bin/sh', '-c', 'env']
      envFrom:
        - secretRef:
            name: test-secret  # load the test-secret into the environment

# kubectl -n configmap-test create secret generic test-secret --from-literal=password=secretvalue
# kubectl -n configmap-test describe secret test-secret
# kubectl -n configmap-test create -f mount-secret-as-env.yaml
# kubectl -n configmap-test logs -f secret-env-pod

