kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeserve
  labels:
    app: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


