apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-7-01
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 150%
  selector:
    matchLabels:
      chapter: controllers
      activity: "1" 
  template:
    metadata:
      labels:
        chapter: controllers
        activity: "1"
    spec:
      containers:
        - name: nginx
          image: nginx

