apiVersion: v1
kind: Pod
metadata:
  name: arbitrary-production-application
  namespace: activity-6-01
  labels:
    owner: product-development
    priorityClassName: system-node-critical
    environment: production
  annotations:
    team-link: "http://product-dev-team"
spec:
  containers:
    - name: arbitrary-production-application
      image: nginx

