apiVersion: v1
kind: Pod
metadata:
  name: command-pod
spec:
  containers:
    - name: container-with-command
      image: ubuntu
      command:
        - /bin/bash
        - -ec
        - while :; do echo '.'; sleep 5; done

# Run with:
#   kubectl create -f this-manifest-filename
# Check with:
#   kubectl logs command-pod -f
