apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  containers:
    - name: my-first-container
      image: nginx

# Create this pod with the command
#   kubectl create -f this_manifest_filename
# Create this pod in a different namespace
#   kubectl --namespace kube-public create -f single-container-pod.yaml
#   here, we cannot use -ns for --namespace, we must use --namespace.
